package com.advent

class EightTest
    extends org.scalatest.wordspec.AnyWordSpec
    with org.scalatest.matchers.should.Matchers {
  "part1" should {
    "work for an example 1" in {
      val input =
        """..........
          |..........
          |..........
          |....a.....
          |..........
          |.....a....
          |..........
          |..........
          |..........
          |..........""".stripMargin
      val arr: Array[Array[Char]] =
        input.split("\n").map(_.trim.toCharArray)
      new Eight().part1(arr) shouldEqual 2
    }

    "work for an example" in {
      val input =
        """............
          |........0...
          |.....0......
          |.......0....
          |....0.......
          |......A.....
          |............
          |............
          |........A...
          |.........A..
          |............
          |............""".stripMargin
      val arr: Array[Array[Char]] =
        input.split("\n").map(_.trim.toCharArray)
      new Eight().part1(arr) shouldEqual 14
    }
  }

  "part2" should {
    "work for an exampl1" in {
      val input =
        """T.........
          |...T......
          |.T........
          |..........
          |..........
          |..........
          |..........
          |..........
          |..........
          |..........""".stripMargin
      val arr: Array[Array[Char]] =
        input.split("\n").map(_.trim.toCharArray)
      new Eight().part2(arr) shouldEqual 9
    }

    "work for an example" in {
      val input =
        """............
          |........0...
          |.....0......
          |.......0....
          |....0.......
          |......A.....
          |............
          |............
          |........A...
          |.........A..
          |............
          |............""".stripMargin
      val arr: Array[Array[Char]] =
        input.split("\n").map(_.trim.toCharArray)
      new Eight().part2(arr) shouldEqual 34
    }
  }
}
